import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateRiskReportPDF = (coinData: any, riskData: any, riskAnalysis: string[]) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(10, 22, 40); // Dark background
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('CryptoGuard', 14, 20);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Risk Analysis Report', 14, 28);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 14, 20, { align: 'right' });

  // Coin Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${coinData.name} (${coinData.symbol.toUpperCase()})`, 14, 55);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Current Price: $${coinData.current_price?.toLocaleString()}`, 14, 63);
  doc.text(`Market Cap: $${coinData.market_cap?.toLocaleString()}`, 14, 70);
  doc.text(`24h Volatility: ${coinData.price_change_percentage_24h?.toFixed(2) || 0}%`, 14, 77);

  const breakdown = riskData?.breakdown || {};
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`RISK BREAKDOWN`, 120, 55);
  doc.setTextColor(0, 0, 0);
  doc.text(`· Volatility Impact: ${breakdown.volatility > 0 ? '+' : ''}${breakdown.volatility || 0}`, 120, 63);
  doc.text(`· Liquidity Impact: ${breakdown.liquidity > 0 ? '+' : ''}${breakdown.liquidity || 0}`, 120, 70);
  doc.text(`· Market Cap Impact: ${breakdown.marketCap > 0 ? '+' : ''}${breakdown.marketCap || 0}`, 120, 77);
  doc.text(`· Whale/Sentiment: ${(breakdown.whaleActivity || 0) + (breakdown.sentiment || 0)}`, 120, 84);

  // Risk Score Section
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(14, 90, 80, 40, 3, 3, 'F');

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('RISK SCORE', 20, 100);

  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');

  const riskScore = typeof riskData === 'number' ? riskData : (riskData?.score || 0);

  let scoreColor = [16, 185, 129]; // Green
  if (riskScore > 60) scoreColor = [239, 68, 68]; // Red
  else if (riskScore > 30) scoreColor = [245, 158, 11]; // Orange

  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(`${riskScore}/100`, 20, 115);

  // Risk Analysis Table
  const tableData = riskAnalysis.map(item => [item]);

  autoTable(doc, {
    startY: 140,
    head: [['AI Risk Assessment Findings']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [124, 58, 237], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 6 },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This report is generated by AI and does not constitute financial advice.', 14, pageHeight - 10);
  doc.text('www.cryptoguard.ai', pageWidth - 14, pageHeight - 10, { align: 'right' });

  doc.save(`${coinData.symbol.toUpperCase()}_Risk_Report.pdf`);
};
